// <auto-generated />
namespace Desafio2.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modificacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202010040300124_modificacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
